const assert=require('node:assert/strict');const {chromium}=require('playwright');const products=require('../data/products.json');
const fs=require('node:fs'), path=require('node:path'), os=require('node:os');
const site=fs.mkdtempSync(path.join(os.tmpdir(),'nexrig-smoke-'));fs.symlinkSync(path.resolve(__dirname,'..'),path.join(site,'nexrig-pc'),'dir');
const server=require('node:child_process').spawn('python3',['-m','http.server','8765','--bind','127.0.0.1','--directory',site],{stdio:'ignore'});process.on('exit',()=>{server.kill();fs.rmSync(site,{recursive:true,force:true});});
(async()=>{
 for(let i=0;i<30;i++){try{await fetch('http://127.0.0.1:8765/nexrig-pc/');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 const browser=await chromium.launch({executablePath:'/usr/lib/chromium/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8765/nexrig-pc/';
 const ready=async p=>p.waitForFunction(()=>Array.from(document.querySelectorAll('[data-add-to-cart]')).every(b=>!b.disabled));
 for(const path of ['', 'en/', 'cartes-graphiques/','processeurs/','en/graphics-cards/','en/processors/','ram/','en/ram/','stockage/','en/storage/','alimentations/','en/power-supplies/','cartes-meres/','en/motherboards/','refroidissement/','en/cooling/','ecrans/','en/monitors/','en/products/kingston-kc3000-1024gb/','produits/intel-core-i7-14700k/','en/products/amd-radeon-rx-7900-xtx/','produits/corsair-vengeance-lpx-16gb-ddr4-3200/','en/products/kingston-fury-beast-32gb-ddr5-6000-kit/','panier/','en/cart/']){
  assert.equal((await page.goto(base+path)).status(),200);await ready(page);
  for(const width of [320,390,768,1024,1200,1201,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${path} ${width}`);}
 }
 // Homepage hamburger works at desktop and mobile widths in both languages.
 for(const homepage of ['', 'en/']){
  await page.goto(base+homepage);await ready(page);
  for(const width of [390,1440]){
   await page.setViewportSize({width,height:900});const menu=page.locator('.menu');const nav=page.locator('#navigation');assert(await menu.isVisible());assert.equal(await menu.getAttribute('aria-expanded'),'false');assert(await nav.evaluate(el=>el.inert));
   await menu.click();assert.equal(await menu.getAttribute('aria-expanded'),'true');await page.locator('#navigation a').first().focus();await page.keyboard.press('Escape');assert.equal(await menu.getAttribute('aria-expanded'),'false');assert(await menu.evaluate(el=>el===document.activeElement));
   await menu.click();await page.locator('#navigation a[href="#components"]').click();assert.equal(await menu.getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>document.activeElement.id),'components');
   await menu.click();await page.mouse.click(5,850);assert.equal(await menu.getAttribute('aria-expanded'),'false');
  }
 }
 for(const product of products.filter(p=>['ram','storage','psu','motherboard','cooling','monitor'].includes(p.category))){await page.goto(base+'produits/'+product.id+'/');await ready(page);await page.setViewportSize({width:320,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'RAM SKU overflow: '+product.id);}
 await page.goto(base+'en/processors/');await ready(page);assert.equal(await page.locator('.shop-card').count(),16);await page.locator('#shop-brand').selectOption('AMD');assert.equal(await page.locator('.shop-card:visible').count(),8);await page.locator('#shop-search').fill('7800');assert.equal(await page.locator('.shop-card:visible').count(),1);await page.locator('#shop-search').fill('nonexistent');assert.equal(await page.locator('.shop-card:visible').count(),0);assert(await page.locator('#shop-empty').isVisible());await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-search').value==='');await page.locator('#shop-sort').selectOption('price-low');
 const sorted=await page.locator('.shop-card:visible').evaluateAll(els=>els.map(el=>el.dataset.productId));const prices=sorted.map(id=>products.find(p=>p.id===id).demo_price_mad);assert.deepEqual(prices,[...prices].sort((a,b)=>a-b));
 await page.goto(base+'en/graphics-cards/');await ready(page);assert.equal(await page.locator('.shop-card').count(),23);await page.locator('#shop-brand').selectOption('ASUS');assert.equal(await page.locator('.shop-card:visible').count(),1);await page.locator('#shop-chip-brand').selectOption('AMD');assert.equal(await page.locator('.shop-card:visible').count(),0);await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-brand').value==='');await page.locator('[data-add-to-cart="asus-dual-rtx-4060-oc"]').click();assert.equal(await page.locator('[data-cart-count]').textContent(),'1');await page.evaluate(()=>localStorage.removeItem('nexrig.demo-cart.v1'));
 await page.goto(base+'cartes-graphiques/');await ready(page);await page.locator('[data-add-to-cart="nvidia-geforce-rtx-4060"]').click();await page.locator('[data-add-to-cart="nvidia-geforce-rtx-4060"]').click();assert.equal(await page.locator('[data-cart-count]').textContent(),'2');await page.goto(base+'processeurs/');await ready(page);await page.locator('[data-add-to-cart="amd-ryzen-5-5600"]').click();await page.locator('[data-cart-link]').click();await page.waitForSelector('.cart-row');assert.equal(await page.locator('.cart-row').count(),2);assert.equal(await page.locator('[data-cart-count]').textContent(),'3');
 const total=async expected=>{const text=await page.locator('#cart-total').textContent();assert(text.replace(/[^0-9]/g,'')===String(expected),text);};await total(9747);
 await page.locator('[data-quantity="nvidia-geforce-rtx-4060"]').fill('3');await page.locator('[data-quantity="nvidia-geforce-rtx-4060"]').press('Tab');await total(13946);await page.reload();await page.waitForSelector('.cart-row');assert.equal(await page.locator('[data-quantity="nvidia-geforce-rtx-4060"]').inputValue(),'3');
 await page.locator('.language-switch').click();await page.waitForURL(base+'en/cart/');await page.waitForSelector('.cart-row');await total(13946);assert.equal(await page.locator('[data-cart-count]').textContent(),'4');
 await page.locator('[data-quantity="nvidia-geforce-rtx-4060"]').fill('0');await page.locator('[data-quantity="nvidia-geforce-rtx-4060"]').press('Tab');assert.equal(await page.locator('[data-quantity="nvidia-geforce-rtx-4060"]').inputValue(),'3');await total(13946);
 await page.locator('[data-remove="amd-ryzen-5-5600"]').click();assert.equal(await page.locator('.cart-row').count(),1);await total(12597);
 const second=await context.newPage();await second.goto(base+'en/products/intel-core-i5-12400f/');await ready(second);await second.locator('button[data-add-to-cart="intel-core-i5-12400f"]').click();await page.waitForFunction(()=>document.querySelectorAll('.cart-row').length===2);await total(14087);await second.close();
 await page.getByRole('button',{name:'Clear cart',exact:true}).click();assert.equal(await page.locator('.cart-row').count(),0);assert(await page.getByText('Your cart is empty.',{exact:true}).isVisible());await total(0);assert(await page.locator('#clear-cart').isDisabled());

 // RAM-specific filters and preservation of CPU/GPU selections from older catalogues.
 await page.goto(base+'en/ram/');await ready(page);assert.equal(await page.locator('.shop-card').count(),24);
 for(const brand of ['Corsair','Kingston','G.Skill','Crucial','TeamGroup','Patriot']){await page.locator('#shop-brand').selectOption(brand);assert.equal(await page.locator('.shop-card:visible').count(),4);}
 await page.locator('#shop-brand').selectOption('Corsair');await page.locator('#shop-generation').selectOption('DDR4');assert.equal(await page.locator('.shop-card:visible').count(),2);await page.locator('#shop-capacity').selectOption('16');assert.equal(await page.locator('.shop-card:visible').count(),1);
 await page.locator('#shop-search').fill('CMK16GX4M2B3200C16');assert.equal(await page.locator('.shop-card:visible').count(),1);await page.locator('#shop-capacity').selectOption('32');assert.equal(await page.locator('.shop-card:visible').count(),0);assert(await page.locator('#shop-empty').isVisible());await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-result').textContent.startsWith('24 / 24'));
 await page.evaluate(()=>localStorage.setItem('nexrig.demo-cart.v1',JSON.stringify([{id:'amd-ryzen-5-5600',quantity:1},{id:'nvidia-geforce-rtx-4060',quantity:2}])));await page.reload();await ready(page);assert.equal(await page.locator('[data-cart-count]').textContent(),'3');
 await page.locator('[data-add-to-cart="corsair-vengeance-lpx-16gb-ddr4-3200"]').click();assert.equal(await page.locator('[data-cart-count]').textContent(),'4');await page.locator('.language-switch').click();await page.waitForURL(base+'ram/');await ready(page);assert.equal(await page.locator('[data-cart-count]').textContent(),'4');
 await page.locator('.shop-card[data-product-id="crucial-pro-overclocking-32gb-ddr5-6000"] .detail-link').click();await ready(page);assert((await page.locator('dl').textContent()).includes('CP2K16G60C36U5B'));await page.locator('[data-add-to-cart="crucial-pro-overclocking-32gb-ddr5-6000"]').click();await page.locator('[data-cart-link]').click();await page.waitForSelector('.cart-row');assert.equal(await page.locator('.cart-row').count(),4);await total(11736);
 await page.locator('[data-quantity="corsair-vengeance-lpx-16gb-ddr4-3200"]').fill('2');await page.locator('[data-quantity="corsair-vengeance-lpx-16gb-ddr4-3200"]').press('Tab');await total(12326);await page.reload();await page.waitForSelector('.cart-row');await total(12326);
 await page.locator('.language-switch').click();await page.waitForURL(base+'en/cart/');await page.waitForSelector('.cart-row');await total(12326);await page.locator('[data-remove="corsair-vengeance-lpx-16gb-ddr4-3200"]').click();await total(11146);await page.getByRole('button',{name:'Clear cart',exact:true}).click();await total(0);
 // Storage filters and a CPU/GPU/RAM/SSD/HDD cart across both languages.
 await page.goto(base+'en/storage/');await ready(page);assert.equal(await page.locator('.shop-card').count(),24);
 for(const brand of ['Samsung','Western Digital','Crucial','Kingston','Seagate','Corsair']){await page.locator('#shop-brand').selectOption(brand);assert.equal(await page.locator('.shop-card:visible').count(),4);}
 await page.locator('#shop-brand').selectOption('');await page.locator('#shop-drive-type').selectOption('SSD');assert.equal(await page.locator('.shop-card:visible').count(),19);
 await page.locator('#shop-drive-type').selectOption('HDD');assert.equal(await page.locator('.shop-card:visible').count(),5);await page.locator('#shop-protocol').selectOption('NVMe');assert.equal(await page.locator('.shop-card:visible').count(),0);
 await page.locator('#shop-drive-type').selectOption('');assert.equal(await page.locator('.shop-card:visible').count(),14);await page.locator('#shop-protocol').selectOption('SATA');assert.equal(await page.locator('.shop-card:visible').count(),10);
 await page.locator('#shop-brand').selectOption('Seagate');await page.locator('#shop-drive-type').selectOption('HDD');await page.locator('#shop-capacity').selectOption('2000');await page.locator('#shop-search').fill('ST2000DM008');assert.equal(await page.locator('.shop-card:visible').count(),1);
 await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-result').textContent.startsWith('24 / 24'));
 const seed=[{id:'amd-ryzen-5-5600',quantity:1},{id:'nvidia-geforce-rtx-4060',quantity:1},{id:'corsair-vengeance-lpx-16gb-ddr4-3200',quantity:1}];await page.evaluate(items=>localStorage.setItem('nexrig.demo-cart.v1',JSON.stringify(items)),seed);await page.reload();await ready(page);
 await page.locator('[data-add-to-cart="samsung-990-pro-2tb"]').click();await page.locator('.language-switch').click();await page.waitForURL(base+'stockage/');await ready(page);assert.equal(await page.locator('[data-cart-count]').textContent(),'4');
 await page.locator('.shop-card[data-product-id="seagate-barracuda-2tb"] .detail-link').click();await ready(page);assert((await page.locator('dl').textContent()).includes('ST2000DM008'));await page.locator('[data-add-to-cart="seagate-barracuda-2tb"]').click();await page.locator('[data-cart-link]').click();await page.waitForSelector('.cart-row');assert.equal(await page.locator('.cart-row').count(),5);
 const baseTotal=seed.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).demo_price_mad,0)+2190;await total(baseTotal+699);
 await page.locator('[data-quantity="seagate-barracuda-2tb"]').fill('2');await page.locator('[data-quantity="seagate-barracuda-2tb"]').press('Tab');await total(baseTotal+1398);await page.reload();await page.waitForSelector('.cart-row');await total(baseTotal+1398);
 await page.locator('.language-switch').click();await page.waitForURL(base+'en/cart/');await page.waitForSelector('.cart-row');await total(baseTotal+1398);await page.locator('[data-remove="seagate-barracuda-2tb"]').click();await total(baseTotal);
 await page.evaluate(()=>localStorage.setItem('nexrig.demo-cart.v1','broken JSON'));await page.reload();await page.waitForSelector('.cart-empty');await total(0);
 await page.evaluate(()=>localStorage.setItem('nexrig.demo-cart.v1',JSON.stringify([{id:'bogus',quantity:3},{id:'amd-ryzen-5-5600',quantity:-1},{id:'amd-ryzen-5-5600',quantity:1.5},{id:'amd-ryzen-5-5600',quantity:100},{id:'amd-ryzen-5-5600',quantity:2,demo_price_mad:1}])));await page.reload();await page.waitForSelector('.cart-row');await total(2698);assert.equal(await page.locator('.cart-row').count(),1);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(site,'cart-mobile.png'),fullPage:true});await page.goto(base+'en/graphics-cards/');await ready(page);await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:path.join(site,'shop-desktop.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(site,'shop-mobile.png'),fullPage:false});
 // Power supply filters, detail additions and mixed-category cart persistence.
 await page.goto(base+'en/power-supplies/');await ready(page);assert.equal(await page.locator('.shop-card').count(),24);
 for(const brand of ['Corsair','Seasonic','be quiet!','Cooler Master','Thermaltake','EVGA']){await page.locator('#shop-brand').selectOption(brand);assert.equal(await page.locator('.shop-card:visible').count(),4);}
 await page.locator('#shop-brand').selectOption('');await page.locator('#shop-wattage').selectOption('750');assert.equal(await page.locator('.shop-card:visible').count(),7);await page.locator('#shop-modularity').selectOption('non-modular');assert.equal(await page.locator('.shop-card:visible').count(),1);
 await page.locator('#shop-wattage').selectOption('');assert.equal(await page.locator('.shop-card:visible').count(),9);await page.locator('#shop-modularity').selectOption('fully-modular');assert.equal(await page.locator('.shop-card:visible').count(),15);await page.locator('#shop-search').fill('nonexistent');assert(await page.locator('#shop-empty').isVisible());await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-result').textContent.startsWith('24 / 24'));
 const psuSeed=['amd-ryzen-5-5600','nvidia-geforce-rtx-4060','corsair-vengeance-lpx-16gb-ddr4-3200','samsung-990-pro-2tb'].map(id=>({id,quantity:1}));await page.evaluate(items=>localStorage.setItem('nexrig.demo-cart.v1',JSON.stringify(items)),psuSeed);await page.reload();await ready(page);
 const firstPsu=products.find(p=>p.category==='psu');const secondPsu=products.find(p=>p.category==='psu'&&p.brand==='Seasonic');await page.locator('[data-add-to-cart="'+firstPsu.id+'"]').click();await page.locator('.language-switch').click();await page.waitForURL(base+'alimentations/');await ready(page);assert.equal(await page.locator('[data-cart-count]').textContent(),'5');await page.goto(base+'produits/'+secondPsu.id+'/');await ready(page);await page.locator('[data-add-to-cart]').first().click();await page.locator('[data-cart-link]').click();await page.waitForSelector('.cart-row');assert.equal(await page.locator('.cart-row').count(),6);
 const psuTotal=psuSeed.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).demo_price_mad,0)+firstPsu.demo_price_mad;await total(psuTotal+secondPsu.demo_price_mad);await page.locator('[data-quantity="'+secondPsu.id+'"]').fill('2');await page.locator('[data-quantity="'+secondPsu.id+'"]').press('Tab');await total(psuTotal+2*secondPsu.demo_price_mad);await page.reload();await page.waitForSelector('.cart-row');await total(psuTotal+2*secondPsu.demo_price_mad);await page.locator('.language-switch').click();await page.waitForURL(base+'en/cart/');await page.waitForSelector('.cart-row');await total(psuTotal+2*secondPsu.demo_price_mad);await page.locator('[data-remove="'+secondPsu.id+'"]').click();await total(psuTotal);
 await page.goto(base+'en/power-supplies/');await ready(page);await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/nexrig-psu-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('.shop-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/nexrig-psu-mobile.png'});
 // Motherboard filters must distinguish platform, DDR generation and physical size.
 await page.goto(base+'en/motherboards/');await ready(page);assert.equal(await page.locator('.shop-card').count(),24);
 for(const brand of ['ASUS','MSI','Gigabyte','ASRock']){await page.locator('#shop-brand').selectOption(brand);assert.equal(await page.locator('.shop-card:visible').count(),6);}
 await page.locator('#shop-brand').selectOption('');for(const socket of ['AM4','AM5','LGA1700']){await page.locator('#shop-socket').selectOption(socket);assert.equal(await page.locator('.shop-card:visible').count(),8);}
 await page.locator('#shop-generation').selectOption('DDR4');assert.equal(await page.locator('.shop-card:visible').count(),4);await page.locator('#shop-generation').selectOption('DDR5');assert.equal(await page.locator('.shop-card:visible').count(),4);await page.locator('#shop-socket').selectOption('AM4');assert.equal(await page.locator('.shop-card:visible').count(),0);assert(await page.locator('#shop-empty').isVisible());await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-result').textContent.startsWith('24 / 24'));
 await page.locator('#shop-form-factor').selectOption('Micro-ATX');assert.equal(await page.locator('.shop-card:visible').count(),12);await page.locator('#shop-socket').selectOption('AM5');assert.equal(await page.locator('.shop-card:visible').count(),4);await page.locator('#shop-brand').selectOption('ASUS');assert.equal(await page.locator('.shop-card:visible').count(),1);await page.locator('#shop-search').fill('B650M-PLUS');assert.equal(await page.locator('.shop-card:visible').count(),1);
 await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-result').textContent.startsWith('24 / 24'));
 const boardSeed=[...psuSeed,{id:firstPsu.id,quantity:1}];await page.evaluate(items=>localStorage.setItem('nexrig.demo-cart.v1',JSON.stringify(items)),boardSeed);await page.reload();await ready(page);const firstBoard=products.find(p=>p.category==='motherboard');const secondBoard=products.find(p=>p.category==='motherboard'&&p.brand==='MSI');await page.locator('[data-add-to-cart="'+firstBoard.id+'"]').click();assert.equal(await page.locator('[data-cart-count]').textContent(),'6');await page.locator('.language-switch').click();await page.waitForURL(base+'cartes-meres/');await ready(page);await page.goto(base+'produits/'+secondBoard.id+'/');await ready(page);await page.locator('[data-add-to-cart]').first().click();await page.locator('[data-cart-link]').click();await page.waitForSelector('.cart-row');assert.equal(await page.locator('.cart-row').count(),7);
 const boardTotal=boardSeed.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).demo_price_mad,0)+firstBoard.demo_price_mad;await total(boardTotal+secondBoard.demo_price_mad);await page.locator('[data-quantity="'+secondBoard.id+'"]').fill('2');await page.locator('[data-quantity="'+secondBoard.id+'"]').press('Tab');await total(boardTotal+2*secondBoard.demo_price_mad);await page.reload();await page.waitForSelector('.cart-row');await total(boardTotal+2*secondBoard.demo_price_mad);await page.locator('.language-switch').click();await page.waitForURL(base+'en/cart/');await page.waitForSelector('.cart-row');await total(boardTotal+2*secondBoard.demo_price_mad);await page.locator('[data-remove="'+secondBoard.id+'"]').click();await total(boardTotal);
 await page.goto(base+'en/motherboards/');await ready(page);await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/nexrig-motherboards-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('.shop-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/nexrig-motherboards-mobile.png'});
 // Air/AIO and radiator filters plus persistent mixed-category cooling selections.
 await page.goto(base+'en/cooling/');await ready(page);assert.equal(await page.locator('.shop-card').count(),24);
 for(const brand of ['Noctua','be quiet!','ARCTIC','DeepCool','Cooler Master','Corsair']){await page.locator('#shop-brand').selectOption(brand);assert.equal(await page.locator('.shop-card:visible').count(),4);}
 await page.locator('#shop-brand').selectOption('');for(const type of ['air','aio']){await page.locator('#shop-cooler-type').selectOption(type);assert.equal(await page.locator('.shop-card:visible').count(),12);}
 for(const [size,count] of [['240',6],['280',1],['360',5]]){await page.locator('#shop-radiator').selectOption(size);assert.equal(await page.locator('.shop-card:visible').count(),count);}
 await page.locator('#shop-cooler-type').selectOption('air');assert.equal(await page.locator('.shop-card:visible').count(),0);assert(await page.locator('#shop-empty').isVisible());await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-result').textContent.startsWith('24 / 24'));await page.locator('#shop-search').fill('NH-L9a-AM5');assert.equal(await page.locator('.shop-card:visible').count(),1);await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-search').value==='');
 const coolingSeed=[...boardSeed,{id:firstBoard.id,quantity:1}];await page.evaluate(items=>localStorage.setItem('nexrig.demo-cart.v1',JSON.stringify(items)),coolingSeed);await page.reload();await ready(page);const firstCooler=products.find(p=>p.category==='cooling');const secondCooler=products.find(p=>p.category==='cooling'&&p.cooler_type==='aio');await page.locator('[data-add-to-cart="'+firstCooler.id+'"]').click();assert.equal(await page.locator('[data-cart-count]').textContent(),'7');await page.locator('.language-switch').click();await page.waitForURL(base+'refroidissement/');await ready(page);await page.goto(base+'produits/'+secondCooler.id+'/');await ready(page);assert((await page.locator('dl').textContent()).includes('240 mm'));await page.locator('[data-add-to-cart]').first().click();await page.locator('[data-cart-link]').click();await page.waitForSelector('.cart-row');assert.equal(await page.locator('.cart-row').count(),8);
 const coolingTotal=coolingSeed.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).demo_price_mad,0)+firstCooler.demo_price_mad;await total(coolingTotal+secondCooler.demo_price_mad);await page.locator('[data-quantity="'+secondCooler.id+'"]').fill('2');await page.locator('[data-quantity="'+secondCooler.id+'"]').press('Tab');await total(coolingTotal+2*secondCooler.demo_price_mad);await page.reload();await page.waitForSelector('.cart-row');await total(coolingTotal+2*secondCooler.demo_price_mad);await page.locator('.language-switch').click();await page.waitForURL(base+'en/cart/');await page.waitForSelector('.cart-row');await total(coolingTotal+2*secondCooler.demo_price_mad);await page.locator('[data-remove="'+secondCooler.id+'"]').click();await total(coolingTotal);
 await page.goto(base+'en/cooling/');await ready(page);await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/nexrig-cooling-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('.shop-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/nexrig-cooling-mobile.png'});
 // Monitor display filters and cart persistence alongside every component category.
 await page.goto(base+'en/monitors/');await ready(page);assert.equal(await page.locator('.shop-card').count(),24);
 for(const brand of ['ASUS','LG','Samsung','AOC','MSI','Gigabyte']){await page.locator('#shop-brand').selectOption(brand);assert.equal(await page.locator('.shop-card:visible').count(),4);}
 await page.locator('#shop-brand').selectOption('');for(const [resolution,count] of [['1920x1080',7],['2560x1440',12],['3840x2160',5]]){await page.locator('#shop-resolution').selectOption(resolution);assert.equal(await page.locator('.shop-card:visible').count(),count);}
 await page.locator('#shop-refresh').selectOption('240');assert.equal(await page.locator('.shop-card:visible').count(),0);assert(await page.locator('#shop-empty').isVisible());await page.locator('#shop-resolution').selectOption('2560x1440');assert.equal(await page.locator('.shop-card:visible').count(),2);await page.locator('#shop-panel').selectOption('VA');assert.equal(await page.locator('.shop-card:visible').count(),1);
 await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-result').textContent.startsWith('24 / 24'));await page.locator('#shop-panel').selectOption('IPS');assert.equal(await page.locator('.shop-card:visible').count(),19);await page.locator('#shop-panel').selectOption('VA');assert.equal(await page.locator('.shop-card:visible').count(),5);await page.locator('#shop-panel').selectOption('');await page.locator('#shop-search').fill('M27Q');assert.equal(await page.locator('.shop-card:visible').count(),1);await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#shop-search').value==='');
 const monitorSeed=[...coolingSeed,{id:firstCooler.id,quantity:1}];await page.evaluate(items=>localStorage.setItem('nexrig.demo-cart.v1',JSON.stringify(items)),monitorSeed);await page.reload();await ready(page);const firstMonitor=products.find(p=>p.category==='monitor');const secondMonitor=products.find(p=>p.category==='monitor'&&p.brand==='LG');await page.locator('[data-add-to-cart="'+firstMonitor.id+'"]').click();assert.equal(await page.locator('[data-cart-count]').textContent(),'8');await page.locator('.language-switch').click();await page.waitForURL(base+'ecrans/');await ready(page);await page.goto(base+'produits/'+secondMonitor.id+'/');await ready(page);assert((await page.locator('dl').textContent()).includes('144 Hz'));await page.locator('[data-add-to-cart]').first().click();await page.locator('[data-cart-link]').click();await page.waitForSelector('.cart-row');assert.equal(await page.locator('.cart-row').count(),9);
 const monitorTotal=monitorSeed.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).demo_price_mad,0)+firstMonitor.demo_price_mad;await total(monitorTotal+secondMonitor.demo_price_mad);await page.locator('[data-quantity="'+secondMonitor.id+'"]').fill('2');await page.locator('[data-quantity="'+secondMonitor.id+'"]').press('Tab');await total(monitorTotal+2*secondMonitor.demo_price_mad);await page.reload();await page.waitForSelector('.cart-row');await total(monitorTotal+2*secondMonitor.demo_price_mad);await page.locator('.language-switch').click();await page.waitForURL(base+'en/cart/');await page.waitForSelector('.cart-row');await total(monitorTotal+2*secondMonitor.demo_price_mad);await page.locator('[data-remove="'+secondMonitor.id+'"]').click();await total(monitorTotal);
 await page.goto(base+'en/monitors/');await ready(page);await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/nexrig-monitors-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('.shop-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/nexrig-monitors-mobile.png'});
 const plain=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const p=await plain.newPage();await p.goto(base+'processeurs/');assert.equal(await p.locator('.shop-card').count(),16);assert(await p.locator('[data-add-to-cart]').first().isDisabled());assert(await p.locator('noscript').isVisible());assert.equal(await p.locator('.shop-filters:visible').count(),0);await p.locator('.detail-link').first().click();assert(await p.locator('h1').isVisible());
 await p.goto(base+'en/motherboards/');assert.equal(await p.locator('.shop-card').count(),24);assert(await p.locator('[data-add-to-cart]').first().isDisabled());await p.locator('.detail-link').first().click();assert((await p.locator('dl').textContent()).includes('DDR4'));
 await p.goto(base+'en/cooling/');assert.equal(await p.locator('.shop-card').count(),24);assert(await p.locator('[data-add-to-cart]').first().isDisabled());await p.locator('.detail-link').first().click();assert((await p.locator('h1').textContent()).includes('Noctua'));
 await p.goto(base+'en/monitors/');assert.equal(await p.locator('.shop-card').count(),24);assert(await p.locator('[data-add-to-cart]').first().isDisabled());await p.locator('.detail-link').first().click();assert((await p.locator('dl').textContent()).includes('IPS'));
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}});});const b=await blocked.newPage();await b.goto(base+'en/processors/');await ready(b);await b.locator('[data-add-to-cart="amd-ryzen-5-5600"]').click();assert.equal(await b.locator('[data-cart-count]').textContent(),'1');assert((await b.locator('#cart-status').textContent()).includes('storage is unavailable'));
 // Simulate old unversioned assets in a returning visitor's browser cache.
 const returning=await browser.newContext();await returning.route('**/assets/js/shop.js',r=>r.fulfill({body:'/* old cached script */',contentType:'application/javascript'}));await returning.route('**/data/products.json',r=>r.fulfill({json:products.filter(p=>p.category!=='ram')}));
 const r=await returning.newPage();await r.goto(base+'ram/');await ready(r);await r.locator('[data-add-to-cart="corsair-vengeance-lpx-16gb-ddr4-3200"]').click();assert.equal(await r.locator('[data-cart-count]').textContent(),'1');await r.locator('[data-cart-link]').click();await r.waitForSelector('.cart-row');assert((await r.locator('.cart-row').textContent()).includes('Corsair Vengeance LPX'));
 // A mismatched CDN response must not overwrite a previously saved RAM selection.
 const stale=await browser.newContext();await stale.addInitScript(()=>localStorage.setItem('nexrig.demo-cart.v1',JSON.stringify([{id:'corsair-vengeance-lpx-16gb-ddr4-3200',quantity:2}])));await stale.route('**/data/products.json*',route=>route.fulfill({json:products.filter(p=>p.category!=='ram')}));const stalePage=await stale.newPage();await stalePage.goto(base+'ram/');await stalePage.waitForFunction(()=>document.querySelector('#cart-status').textContent.length>0);assert(await stalePage.locator('[data-add-to-cart]').first().isDisabled());assert.equal(JSON.parse(await stalePage.evaluate(()=>localStorage.getItem('nexrig.demo-cart.v1')))[0].quantity,2);
 const failed=await browser.newContext();await failed.route('**/data/products.json*',r=>r.fulfill({status:503,body:'unavailable'}));const f=await failed.newPage();await f.goto(base+'en/graphics-cards/');await f.waitForFunction(()=>document.querySelector('#cart-status').textContent.includes('could not load'));assert(await f.locator('[data-add-to-cart]').first().isDisabled());
 await page.goto(base+'en/storage/');await ready(page);await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/nexrig-storage-desktop.png',fullPage:false});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/nexrig-storage-mobile.png',fullPage:false});await page.locator('.shop-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/nexrig-storage-products-mobile.png',fullPage:false});
 assert.deepEqual(errors,[]);console.log('PASS: monitor filters, bilingual pages and mixed-category cart; cooling filters, bilingual pages and mixed-category cart; motherboard filters, bilingual pages and mixed-category cart; PSU filters, product pages and mixed-category cart; storage filters and mixed CPU/GPU/RAM/SSD/HDD cart; RAM brands/generation/capacity/SKU filters, mixed-category cart persistence, RAM product pages,  responsive layouts, 16-model categories, filters/reset/sort, repeated adds, real computed totals, quantity edits/validation, removal/clear, reload/language/cross-tab persistence, malformed storage, untrusted stored prices, no-JS fallback, blocked storage and failed-fetch handling; no page errors.');await browser.close();server.kill();
})().catch(e=>{console.error(e);process.exit(1)});
