const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'nexrig-hover-'));fs.symlinkSync(path.resolve(__dirname,'..'),path.join(dir,'nexrig-pc'),'dir');const server=require('child_process').spawn('python3',['-m','http.server','8768','--bind','127.0.0.1','--directory',dir],{stdio:'ignore'});
(async()=>{let b;try{for(let i=0;i<30;i++){try{await fetch('http://127.0.0.1:8768/');break}catch{await new Promise(r=>setTimeout(r,100));}}b=await chromium.launch({executablePath:'/usr/lib/chromium/chromium',args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1440,height:900}});
for(const route of ['','en/','processeurs/','en/processors/','en/products/amd-ryzen-5-5600/','en/pc-builder/','en/cart/']){
 await p.goto('http://127.0.0.1:8768/nexrig-pc/'+route);await p.waitForSelector('.responsive-navigation');const nav=p.locator('.primary-navigation');const links=await nav.locator('a').evaluateAll(els=>els.map(e=>[e.getAttribute('href'),e.textContent]));
 await p.setViewportSize({width:1440,height:900});assert(!await p.locator('.menu').isVisible());assert(await nav.isVisible());await nav.locator('.nav-group-toggle').first().hover();await p.waitForFunction(()=>document.querySelector('.nav-group').hasAttribute('open'));assert.equal(await nav.locator('.nav-group-links').first().evaluate(e=>getComputedStyle(e).display),'grid');assert.equal(await nav.locator('.nav-group-links').first().evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),3);
 await p.mouse.move(5,899);await p.setViewportSize({width:390,height:844});assert(await p.locator('.menu').isVisible());await p.locator('.menu').click();assert(await nav.isVisible());assert.equal(Math.round((await nav.boundingBox()).height),844);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(await nav.locator('a').evaluateAll(els=>els.map(e=>[e.getAttribute('href'),e.textContent])),links);
 await p.keyboard.press('Escape');assert.equal(await p.locator('.menu').getAttribute('aria-expanded'),'false');await p.setViewportSize({width:1100,height:900});await p.waitForFunction(()=>!document.querySelector('.primary-navigation').inert);assert(!await p.locator('.menu').isVisible());
 if(route==='en/'){await p.screenshot({path:'/tmp/nexrig-desktop-navigation.png'});}
}
const context=await b.newContext({hasTouch:true,isMobile:true,viewport:{width:390,height:844}}),mobile=await context.newPage();await mobile.goto('http://127.0.0.1:8768/nexrig-pc/en/');await mobile.locator('.menu').tap();await mobile.waitForFunction(()=>getComputedStyle(document.querySelector('.primary-navigation')).transform==='matrix(1, 0, 0, 1, 0, 0)');for(const group of [0,1]){const summary=mobile.locator('.nav-group-toggle').nth(group),box=await summary.boundingBox();const before=mobile.url();await mobile.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);assert.equal(mobile.url(),before);assert(await mobile.locator('.nav-group').nth(group).evaluate(e=>e.hasAttribute('open')));await mobile.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);assert(!await mobile.locator('.nav-group').nth(group).evaluate(e=>e.hasAttribute('open')));assert.equal(await summary.getAttribute('aria-expanded'),'false');const linkBox=await mobile.locator('.nav-hub-link').nth(group).boundingBox();assert(box.width>=56&&box.height>=56);assert(box.x>=linkBox.x+linkBox.width+8);await summary.focus();await mobile.keyboard.press('Enter');assert.equal(await summary.getAttribute('aria-expanded'),'true');await mobile.keyboard.press('Space');assert.equal(await summary.getAttribute('aria-expanded'),'false');}
await mobile.locator('.nav-hub-link').first().tap();await mobile.waitForURL('**/en/components/');await mobile.locator('.menu').tap();await mobile.locator('.nav-hub-link').nth(1).tap();await mobile.waitForURL('**/en/accessories/');await mobile.locator('.menu').tap();await mobile.screenshot({path:'/tmp/nexrig-mobile-navigation.png'});console.log('PASS desktop mega menu, mobile drawer height, preserved links, breakpoint resize, Escape and touch across page types.');}finally{if(b)await b.close();server.kill();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
